// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SNY8SKpWJdsjcDPN3h6sIO71lMJryB8',
    appId: '1:472752504063:web:2fa46c19b2e1f3392fa0ca',
    messagingSenderId: '472752504063',
    projectId: 'login-application-c08a6',
    authDomain: 'login-application-c08a6.firebaseapp.com',
    storageBucket: 'login-application-c08a6.firebasestorage.app',
    measurementId: 'G-VRDFBE2BD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8e4C5Ad2YMCsxms2dQkwJVkmrT55bM-g',
    appId: '1:472752504063:android:b62886fcabbbf9682fa0ca',
    messagingSenderId: '472752504063',
    projectId: 'login-application-c08a6',
    storageBucket: 'login-application-c08a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFp0Kr9EFW_U55ttROIFc4xsbaRWwB-rA',
    appId: '1:472752504063:ios:fbd437f8a7a7f7572fa0ca',
    messagingSenderId: '472752504063',
    projectId: 'login-application-c08a6',
    storageBucket: 'login-application-c08a6.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFp0Kr9EFW_U55ttROIFc4xsbaRWwB-rA',
    appId: '1:472752504063:ios:fbd437f8a7a7f7572fa0ca',
    messagingSenderId: '472752504063',
    projectId: 'login-application-c08a6',
    storageBucket: 'login-application-c08a6.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8SNY8SKpWJdsjcDPN3h6sIO71lMJryB8',
    appId: '1:472752504063:web:dc676315a9a300a02fa0ca',
    messagingSenderId: '472752504063',
    projectId: 'login-application-c08a6',
    authDomain: 'login-application-c08a6.firebaseapp.com',
    storageBucket: 'login-application-c08a6.firebasestorage.app',
    measurementId: 'G-WQ5R8R2259',
  );
}
